fix an error ocurring after opening a graph + change the way of save
Buttle/ButtleOFX/buttleofx/data/buttleData.py", line 497, in loadData
for index, view in decoded["viewer"]["other_views"].iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
iteritems() is no longer available because it is a python 2 method, in
python 3 it is items()